lsi: false
safe: true
source: [main]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/hacker@v0.2.0
plugins: jekyll-remote-theme 
theme: Hacker
